// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using univo.data;

namespace univo.Migrations
{
    [DbContext(typeof(univoContext))]
    partial class univoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("univo.Models.Boletas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("borrado")
                        .HasColumnType("bit");

                    b.Property<int?>("carrerasid")
                        .HasColumnType("int");

                    b.Property<string>("detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("devuelto")
                        .HasColumnType("bit");

                    b.Property<string>("encargado")
                        .IsRequired()
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.Property<int?>("facultadesid")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("idcarrera")
                        .HasColumnType("int");

                    b.Property<int>("idfacultad")
                        .HasColumnType("int");

                    b.Property<int>("idusuario")
                        .HasColumnType("int");

                    b.Property<string>("materia")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int?>("usuariosid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("carrerasid");

                    b.HasIndex("facultadesid");

                    b.HasIndex("usuariosid");

                    b.ToTable("boletas");
                });

            modelBuilder.Entity("univo.Models.BoletasDetalles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProductosId")
                        .HasColumnType("int");

                    b.Property<int?>("boletasid")
                        .HasColumnType("int");

                    b.Property<bool>("borrado")
                        .HasColumnType("bit");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("iddetalle")
                        .HasColumnType("int");

                    b.Property<int>("idproducto")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ProductosId");

                    b.HasIndex("boletasid");

                    b.ToTable("boletasdetalles");
                });

            modelBuilder.Entity("univo.Models.Carreras", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("borrado")
                        .HasColumnType("bit");

                    b.Property<string>("carrerra")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("facultadesid")
                        .HasColumnType("int");

                    b.Property<int>("idfacultad")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("facultadesid");

                    b.ToTable("carreras");
                });

            modelBuilder.Entity("univo.Models.Facultades", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("borrado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("facultades");
                });

            modelBuilder.Entity("univo.Models.Modulos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("borrado")
                        .HasColumnType("bit");

                    b.Property<string>("modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("modulos");
                });

            modelBuilder.Entity("univo.Models.Movimientos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

<<<<<<< HEAD
                    b.Property<bool>("borrado")
                        .HasColumnType("bit");

                    b.Property<string>("concepto")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

=======
>>>>>>> 68029ef6733b964cafc9f3551ae6f918282ff6ba
                    b.Property<string>("documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

<<<<<<< HEAD
                    b.Property<int>("entrada")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("idproducto")
                        .HasColumnType("int");

                    b.Property<int>("idusuario")
                        .HasColumnType("int");

                    b.Property<int?>("productosId")
                        .HasColumnType("int");

                    b.Property<int>("saldo")
                        .HasColumnType("int");

                    b.Property<int>("salida")
                        .HasColumnType("int");

                    b.Property<int?>("usuariosid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("productosId");

                    b.HasIndex("usuariosid");

=======
                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("id");

>>>>>>> 68029ef6733b964cafc9f3551ae6f918282ff6ba
                    b.ToTable("movimientos");
                });

            modelBuilder.Entity("univo.Models.Productos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("borrado")
                        .HasColumnType("bit");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("detalle")
                        .HasColumnType("text");

                    b.Property<int>("existencia")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("marca")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(75)")
                        .HasMaxLength(75);

                    b.HasKey("Id");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("univo.Models.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("borrado")
                        .HasColumnType("bit");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("univo.Models.RolesPermisos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("borrar")
                        .HasColumnType("bit");

                    b.Property<bool>("crear")
                        .HasColumnType("bit");

                    b.Property<bool>("editar")
                        .HasColumnType("bit");

                    b.Property<bool>("imprimir")
                        .HasColumnType("bit");

                    b.Property<int>("moduloid")
                        .HasColumnType("int");

                    b.Property<int>("rolid")
                        .HasColumnType("int");

                    b.Property<bool>("visualizar")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("moduloid");

                    b.HasIndex("rolid");

                    b.ToTable("roles_permisos");
                });

            modelBuilder.Entity("univo.Models.Usuarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("borrado")
                        .HasColumnType("bit");

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("rolid")
                        .HasColumnType("int");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.HasIndex("rolid");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("univo.Models.Boletas", b =>
                {
                    b.HasOne("univo.Models.Carreras", "carreras")
                        .WithMany("boletas")
                        .HasForeignKey("carrerasid");

                    b.HasOne("univo.Models.Facultades", "facultades")
                        .WithMany("boletas")
                        .HasForeignKey("facultadesid");

                    b.HasOne("univo.Models.Usuarios", "usuarios")
                        .WithMany("boletas")
                        .HasForeignKey("usuariosid");
                });

            modelBuilder.Entity("univo.Models.BoletasDetalles", b =>
                {
                    b.HasOne("univo.Models.Productos", "Productos")
                        .WithMany("boletasdetalles")
                        .HasForeignKey("ProductosId");

                    b.HasOne("univo.Models.Boletas", "boletas")
                        .WithMany("boletadetalles")
                        .HasForeignKey("boletasid");
                });

            modelBuilder.Entity("univo.Models.Carreras", b =>
                {
                    b.HasOne("univo.Models.Facultades", "facultades")
                        .WithMany("carreras")
                        .HasForeignKey("facultadesid");
                });

            modelBuilder.Entity("univo.Models.Movimientos", b =>
                {
                    b.HasOne("univo.Models.Productos", "productos")
                        .WithMany("movimientos")
                        .HasForeignKey("productosId");

                    b.HasOne("univo.Models.Usuarios", "usuarios")
                        .WithMany("movimientos")
                        .HasForeignKey("usuariosid");
                });

            modelBuilder.Entity("univo.Models.RolesPermisos", b =>
                {
                    b.HasOne("univo.Models.Modulos", "modulo")
                        .WithMany("rolespermisos")
                        .HasForeignKey("moduloid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("univo.Models.Roles", "rol")
                        .WithMany("rolespermisos")
                        .HasForeignKey("rolid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("univo.Models.Usuarios", b =>
                {
                    b.HasOne("univo.Models.Roles", "rol")
                        .WithMany()
                        .HasForeignKey("rolid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
